### PR TITLE
JVM target incompatibility fix for issue #43

### LINKED ISSUE #43: jvm target incompatibility
Getting this error:

Execution failed for task ':update_available_android:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.

if we have in android/settings.gradle the following config then it works:
```plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
}
```

but if the above are changed to:
```plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.0.2" apply false
    id "org.jetbrains.kotlin.android" version "1.9.0" apply false
}
```
 then the error is recieved.

update_available version: 3.1.0+1

### PR DESCRIPTION
**Pull request by SushantSangle**
## Main Objective -> Resolve #43 
- This issue is caused when default JVM used by android studio is other than JDK 17 or earlier. setting kotlin jvm version manually prevents incompatibility issue from popping up. 

### Changed Build Configuration:

* [`update_available_android/android/build.gradle`](diffhunk://#diff-d220f8c14adc0ec3902fbf13d003676fb0db17a83170dd38c806e8816bb0d11aR27-R30): Added Kotlin JVM toolchain configuration to use version 17.
---

## Dart formatting

- This pull request also includes several formatting changes across multiple files to improve code readability and maintain consistency. 
- This also helps this library achieve 160/160 points on pub.dev

### CODE REVIEW

File: update_available/example/lib/main.dart [hunk 1]
```diff
@@ -71,7 +72,8 @@ class _UpdateAvailableExampleState extends State<UpdateAvailableExample> {
       text = switch (availability) {
         UpdateAvailable() => "There's an update available!",
         NoUpdateAvailable() => "There's no update available!",
-        UnknownAvailability() => "Sorry, couldn't determine if there is or not an available update!",
+        UnknownAvailability() =>
+          "Sorry, couldn't determine if there is or not an available update!",
```
Comment (mateusfccp) [inline update_available/example/lib/main.dart:76]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available/example/lib/main.dart [hunk 2]
```diff
@@ -24,7 +24,8 @@ class _UpdateAvailableExampleState extends State<UpdateAvailableExample> {
       color: green,
       pageRouteBuilder: <T>(RouteSettings settings, WidgetBuilder builder) {
         return PageRouteBuilder(
-          pageBuilder: (context, animation, secondaryAnimation) => builder(context),
+          pageBuilder: (context, animation, secondaryAnimation) =>
+              builder(context),
```
Comment (mateusfccp) [inline update_available/example/lib/main.dart:28]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_android/android/build.gradle [hunk 3]
```diff
@@ -24,6 +24,10 @@ rootProject.allprojects {
 apply plugin: 'com.android.library'
 apply plugin: 'kotlin-android'
 
+kotlin {
+    jvmToolchain(17)
```
Comment (mateusfccp) [inline update_available_android/android/build.gradle:28]: Will this keep working for newer versions of the JVM?

File: update_available_android/lib/update_available_android.dart [hunk 4]
```diff
@@ -11,14 +11,17 @@ final class UpdateAvailableAndroidPlugin extends UpdateAvailablePlatform {
   }
 
   @override
-  Future<Availability> getUpdateAvailability({String? iosAppStoreRegion}) async {
+  Future<Availability> getUpdateAvailability(
+      {String? iosAppStoreRegion}) async {
```
Comment (mateusfccp) [inline update_available_android/lib/update_available_android.dart:15]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_android/lib/update_available_android.dart [hunk 5]
```diff
@@ -11,14 +11,17 @@ final class UpdateAvailableAndroidPlugin extends UpdateAvailablePlatform {
...
     try {
-      final available = await platform.invokeMethod<bool>('getUpdateAvailability');
+      final available =
+          await platform.invokeMethod<bool>('getUpdateAvailability');
```
Comment (mateusfccp) [inline update_available_android/lib/update_available_android.dart:18]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_android/lib/update_available_android.dart [hunk 6]
```diff
@@ -11,14 +11,17 @@ final class UpdateAvailableAndroidPlugin extends UpdateAvailablePlatform {
...
 
       return switch (available) {
         true => const UpdateAvailable(),
         false => const NoUpdateAvailable(),
-        null => throw StateError("The implementation should return either 'true' or 'false'. This means that there's an issue with the implementation."),
+        null => throw StateError(
+            "The implementation should return either 'true' or 'false'. This means that there's an issue with the implementation."),
```
Comment (mateusfccp) [inline update_available_android/lib/update_available_android.dart:24]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_ios/lib/adapters/get_ios_package_version_impl.dart [hunk 7]
```diff
@@ -17,7 +17,8 @@ GetIOSPackageVersion httpGetIOSPackageVersion() {
     if (iosAppStoreRegion == null) {
       uri = Uri.parse('$_itunesURL/lookup?bundleId=$bundleId&_=$timestamp');
     } else {
-      uri = Uri.parse('$_itunesURL/$iosAppStoreRegion/lookup?bundleId=$bundleId&_=$timestamp');
+      uri = Uri.parse(
+          '$_itunesURL/$iosAppStoreRegion/lookup?bundleId=$bundleId&_=$timestamp');
```
Comment (mateusfccp) [inline update_available_ios/lib/adapters/get_ios_package_version_impl.dart:21]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_ios/lib/domain/get_ios_package_version.dart [hunk 8]
```diff
@@ -2,4 +2,5 @@ import 'dart:async';
 
 import 'package:pub_semver/pub_semver.dart';
 
-typedef GetIOSPackageVersion = Future<Version?> Function(String, {String? iosAppStoreRegion});
+typedef GetIOSPackageVersion = Future<Version?> Function(String,
+    {String? iosAppStoreRegion});
```
Comment (mateusfccp) [inline update_available_ios/lib/domain/get_ios_package_version.dart:6]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_ios/lib/update_available_ios.dart [hunk 9]
```diff
@@ -31,16 +31,20 @@ final class UpdateAvailableIosPlugin extends UpdateAvailablePlatform {
   }
 
   @override
-  Future<Availability> getUpdateAvailability({String? iosAppStoreRegion}) async {
+  Future<Availability> getUpdateAvailability(
+      {String? iosAppStoreRegion}) async {
```
Comment (mateusfccp) [inline update_available_ios/lib/update_available_ios.dart:35]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_ios/lib/update_available_ios.dart [hunk 10]
```diff
@@ -31,16 +31,20 @@ final class UpdateAvailableIosPlugin extends UpdateAvailablePlatform {
...
     try {
       final bundleId = await getIOSBundleId();
-      final packageVersion = await getIOSPackageVersion(bundleId, iosAppStoreRegion: iosAppStoreRegion);
+      final packageVersion = await getIOSPackageVersion(bundleId,
+          iosAppStoreRegion: iosAppStoreRegion);
```
Comment (mateusfccp) [inline update_available_ios/lib/update_available_ios.dart:39]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_ios/lib/update_available_ios.dart [hunk 11]
```diff
@@ -31,16 +31,20 @@ final class UpdateAvailableIosPlugin extends UpdateAvailablePlatform {
...
       final version = await getIOSVersion();
 
       if (version == null || packageVersion == null) {
         return const UnknownAvailability();
       } else {
-        return packageVersion > version ? const UpdateAvailable() : const NoUpdateAvailable();
+        return packageVersion > version
+            ? const UpdateAvailable()
+            : const NoUpdateAvailable();
```
Comment (mateusfccp) [inline update_available_ios/lib/update_available_ios.dart:47]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_ios/test/adapters/get_ios_package_version_impl_test.dart [hunk 12]
```diff
@@ -11,7 +11,8 @@ void main() {
       expect(version, isNull);
     });
 
-    test('should get the latest version of getVersion given bundle ID', () async {
+    test('should get the latest version of getVersion given bundle ID',
+        () async {
```
Comment (mateusfccp) [inline update_available_ios/test/adapters/get_ios_package_version_impl_test.dart:15]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_ios/test/update_available_ios_test.dart [hunk 13]
```diff
@@ -16,7 +16,8 @@ void main() {
         );
 
         // Assert
-        expect(await plugin.getUpdateAvailability(), const UnknownAvailability());
+        expect(
+            await plugin.getUpdateAvailability(), const UnknownAvailability());
```
Comment (mateusfccp) [inline update_available_ios/test/update_available_ios_test.dart:20]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_ios/test/update_available_ios_test.dart [hunk 14]
```diff
@@ -26,12 +27,14 @@ void main() {
         // Arrange
         final plugin = UpdateAvailableIosPlugin(
           getIOSBundleId: () async => 'fakeId',
-          getIOSPackageVersion: (_, {iosAppStoreRegion}) async => Version(1, 0, 0),
+          getIOSPackageVersion: (_, {iosAppStoreRegion}) async =>
+              Version(1, 0, 0),
```
Comment (mateusfccp) [inline update_available_ios/test/update_available_ios_test.dart:31]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_ios/test/update_available_ios_test.dart [hunk 15]
```diff
@@ -26,12 +27,14 @@ void main() {
...
           getIOSVersion: () async => null,
         );
 
         // Assert
-        expect(await plugin.getUpdateAvailability(), const UnknownAvailability());
+        expect(
+            await plugin.getUpdateAvailability(), const UnknownAvailability());
```
Comment (mateusfccp) [inline update_available_ios/test/update_available_ios_test.dart:37]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_ios/test/update_available_ios_test.dart [hunk 16]
```diff
@@ -41,7 +44,8 @@ void main() {
         // Arrange
         final plugin = UpdateAvailableIosPlugin(
           getIOSBundleId: () async => 'fakeId',
-          getIOSPackageVersion: (_, {iosAppStoreRegion}) async => Version(1, 1, 0),
+          getIOSPackageVersion: (_, {iosAppStoreRegion}) async =>
+              Version(1, 1, 0),
```
Comment (mateusfccp) [inline update_available_ios/test/update_available_ios_test.dart:48]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_ios/test/update_available_ios_test.dart [hunk 17]
```diff
@@ -56,7 +60,8 @@ void main() {
         // Arrange
         final plugin = UpdateAvailableIosPlugin(
           getIOSBundleId: () async => 'fakeId',
-          getIOSPackageVersion: (_, {iosAppStoreRegion}) async => Version(1, 0, 0),
+          getIOSPackageVersion: (_, {iosAppStoreRegion}) async =>
+              Version(1, 0, 0),
```
Comment (mateusfccp) [inline update_available_ios/test/update_available_ios_test.dart:64]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: update_available_ios/test/update_available_ios_test.dart [hunk 18]
```diff
@@ -71,7 +76,8 @@ void main() {
...
```
Comment (mateusfccp) [inline update_available_ios/test/update_available_ios_test.dart:80]: I don't use 80 as my line width, and I expect this to be kept as is. Please, open a different issue if you think this should be changed.

File: .gitignore [hunk 19]
```diff
@@ -1 +1,2 @@
-**/.DS_Store
\ No newline at end of file
+**/.DS_Store
+.idea
```
Comment (mateusfccp) [inline .gitignore:2]: Nice one.

**Review by mateusfccp — CHANGES_REQUESTED** [review]

File: update_available_android/android/build.gradle (hunk 3 above)
Comment (SushantSangle) [reply update_available_android/android/build.gradle:28]: No this should not break in newer versions of JVM as jvmToolChain version for kotlin and jvmToolChain version for java are now both 17 in this project.

This gives more details about this configuration. 
https://kotlinlang.org/docs/gradle-configure-project.html#kotlin-and-java-sources

Gradle while operating on another java version can still use the version specified in these variables to build certain parts of a project.

File: update_available_android/lib/update_available_android.dart (hunk 4 above)
Comment (SushantSangle) [reply update_available_android/lib/update_available_android.dart:15]: Ok I'll update the PR accordingly

File: update_available_android/lib/update_available_android.dart (hunk 5 above)
Comment (SushantSangle) [reply update_available_android/lib/update_available_android.dart:18]: Ok I'll update the PR accordingly

**Comment by mateusfccp** [comment]
I'm going to accept this, as I couldn't reproduce the issue locally. I will revert it if anyone find any issue using the package after this lands.

**Review by mateusfccp — APPROVED** [review]

**Comment by mateusfccp** [comment]
@SushantSangle Can you rebase so all your commits are verified?

**Comment by SushantSangle** [comment]
@mateusfccp rebase complete

**Comment by mateusfccp** [comment]
@SushantSangle Thanks for your contribution!
