### PR TITLE
iOS version: force itunes to unvalidate its cache

### LINKED ISSUE #44: iOS version not working?
Hi there,

Just to report that the plugin does not seem to work anymore ("at least" on iOS).

I uploaded the latest version of [my app](https://apps.apple.com/in/app/nomad-park/id6470134352) 2 days ago, and `getUpdateAvailability` keeps returning `NoUpdateAvailable()`...

I had tried a few weeks before by downgrading the test version I was building and it was working fine. For example the version on the app store was `1.2.6+195`. So I changed my `pubspec.yaml` to `version: 1.2.5+193` and I would run a `flutter run --release` on my test device, and `getUpdateAvailability()` would return `UpdateAvailable()`.

This is not the case anymore, and will only return `NoUpdateAvailable()`

- iOS version 17.5.1
- Flutter 3.24.1
```bash
flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

The is a snippet of my code:
```dart
class AppUpdateAvailableProvider extends CustomChangeNotifier {
  bool updateAvailable = false;

  init() {
    makePeriodicTimer(const Duration(minutes: 30), _checkUpdate, fireNow: true);
  }

  Future<void> _checkUpdate(Timer _) async {
    beingLoaded = true;
    getUpdateAvailability().then((Availability updateAvailability) {
      updateAvailable = updateAvailability == const UpdateAvailable();
      if (updateAvailable) {
        notifyListeners();
      }
      maybeCompleteDataLoadedFuture();
    });
  }
```

### PR DESCRIPTION
**Pull request by millerf**
Fixes #44 

Forces Itunes to invalidate its cache and prevent sending outdated version.

#### First approach

I tried using `no-cache` headers

```dart
// Prevent server-side cache
request.headers.add(HttpHeaders.cacheControlHeader, "no-cache, no-store, must-revalidate");
```

However iTunes CDN does not seem to accept them.

#### Second approach

I added a random string in the URL. It feels a bit hacky, so I am not sure if you want to use this PR. Up to you.

### CODE REVIEW

**Comment by mateusfccp** [comment]
I looked at how `upgrader` do, and they also use a "cache buster" (as they call).

I think their approach is more sensible, as it's virtually impossible to have the same code generated. They used `DateTime` to get the current timestamp.

You can see it here:

https://github.com/larryaasen/upgrader/blob/fa02d08e4d68dd43f4c0392f093ac609c744e453/lib/src/itunes_search_api.dart#L131

File: update_available_ios/lib/adapters/get_ios_package_version_impl.dart [hunk 1]
```diff
@@ -24,7 +27,6 @@ GetIOSPackageVersion httpGetIOSPackageVersion() {
     final responseBody = await response.transform(utf8.decoder).join();
 
     final versionString = getStringByKey(responseBody)('version');
-
```
Comment (mateusfccp) [inline update_available_ios/lib/adapters/get_ios_package_version_impl.dart:27]: Not related to the PR, please revert.

File: update_available_ios/lib/adapters/get_ios_package_version_impl.dart [hunk 2]
```diff
@@ -5,17 +5,20 @@ import 'package:pub_semver/pub_semver.dart';
...
 import 'json.dart';
+import 'dart:math';
 
 const _itunesURL = 'https://itunes.apple.com';
 
 GetIOSPackageVersion httpGetIOSPackageVersion() {
   return (String bundleId, {String? iosAppStoreRegion}) async {
     final Uri uri;
 
+    Random random = new Random();
```
Comment (mateusfccp) [inline update_available_ios/lib/adapters/get_ios_package_version_impl.dart:16]:
```suggestion
    final random = Random();
```

File: update_available_ios/lib/adapters/get_ios_package_version_impl.dart [hunk 3]
```diff
@@ -5,17 +5,20 @@ import 'package:pub_semver/pub_semver.dart';
...
+    int randomNumber = random.nextInt(1000);
```
Comment (mateusfccp) [inline update_available_ios/lib/adapters/get_ios_package_version_impl.dart:17]:
```suggestion
    final randomNumber = random.nextInt(1000);
```

**Review by mateusfccp — CHANGES_REQUESTED** [review]

**Comment by millerf** [comment]
> I looked at how `upgrader` do, and they also use a "cache buster" (as they call).
> 
> I think their approach is more sensible, as it's virtually impossible to have the same code generated. They used `DateTime` to get the current timestamp.
> 
> You can see it here:
> 
> https://github.com/larryaasen/upgrader/blob/fa02d08e4d68dd43f4c0392f093ac609c744e453/lib/src/itunes_search_api.dart#L131

Sorry this was not properly written. When I realised it was somewhat hacky, I did not push it too much.
If you think you want to land this "cache custer"  approach, I'll definitely clean it.

**Comment by mateusfccp** [comment]
> > I looked at how `upgrader` do, and they also use a "cache buster" (as they call).
> > I think their approach is more sensible, as it's virtually impossible to have the same code generated. They used `DateTime` to get the current timestamp.
> > You can see it here:
> > https://github.com/larryaasen/upgrader/blob/fa02d08e4d68dd43f4c0392f093ac609c744e453/lib/src/itunes_search_api.dart#L131
> 
> Sorry this was not properly written. When I realised it was somewhat hacky, I did not push it too much. If you think you want to land this "cache custer" approach, I'll definitely clean it.

I wouldn't call it exactly hacky. I don't know why it's being cached, but this approach is something that's actually used a lot in web development to prevent browser caching.

However, I think using `DateTime` instead of `Random` is a more reasonable approach. If you can implement it this way, I'll be glad to merge your MR.

**Comment by millerf** [comment]
> I wouldn't call it exactly hacky. I don't know why it's being cached, but this approach is something that's actually used a lot in web development to prevent browser caching.

I know, however bypassing a server's cache could have more unforeseen issues (such as being blacklisted). But I guess in that case it does not really matter.

I implemented the change and used a timestamp, which is evidently a better approach.

File: update_available_ios/lib/adapters/get_ios_package_version_impl.dart [hunk 4]
```diff
@@ -12,10 +12,12 @@ GetIOSPackageVersion httpGetIOSPackageVersion() {
   return (String bundleId, {String? iosAppStoreRegion}) async {
     final Uri uri;
 
+    // Busting iTunes CDN cache
+    final String timeStamp = DateTime.now().millisecondsSinceEpoch.toString();
```
Comment (mateusfccp) [inline update_available_ios/lib/adapters/get_ios_package_version_impl.dart:16]:
```suggestion
    final timestamp = DateTime.now().millisecondsSinceEpoch;
```

* Timestamp is a single word, so the correct capitalization would be `timestamp`;
* This repository follows Effective Dart, which says "local variables shouldn't have type annotations and should be declared using just `var` or `final`";
* `toString()` is not necessary here, since string interpolation implicitly calls it.

Comment (mateusfccp) [reply update_available_ios/lib/adapters/get_ios_package_version_impl.dart:16]: Change the other occurrences of `timeStamp` to `timestamp` too.

**Review by mateusfccp — CHANGES_REQUESTED** [review]

**Comment by millerf** [comment]
> Please, add a `## Unreleased` version to the changelogs with this change described and pointing to the issue

Done.

**Comment by millerf** [comment]
Feel free to update the changelog description to your liking :)

**Comment by mateusfccp** [comment]
A test has failed, can you please have a look?

**Comment by millerf** [comment]
@mateusfccp Tests are passing locally. URL called is https://itunes.apple.com/lookup?bundleId=org.adventistas.armsa&_=1724680668385 and works fine.
I'll restart them with an empty commit.

**Review by mateusfccp — APPROVED** [review]

**Comment by mateusfccp** [comment]
@millerf LGTM, can you sign your commits as required by the branch rules?

**Comment by millerf** [comment]
@mateusfccp Done. Sorry I have been busy...

**Comment by mateusfccp** [comment]
No problem, thanks for your contribution.

**Comment by millerf** [comment]
@mateusfccp Could you deploy the new version on flutter.dev when you get a chance?

**Comment by mateusfccp** [comment]
> @mateusfccp Could you deploy the new version on flutter.dev when you get a chance?

Yes, I would like to solve #43 before doing it, but I'm not sure if I'll be able to do it immediately.

**Comment by millerf** [comment]
> > @mateusfccp Could you deploy the new version on flutter.dev when you get a chance?
> 

I see! No worries. I can still override the repo with my branch if needed. No rush.

**Comment by millerf** [comment]
Please let me know when this is available, so I can remove my override ;)

**Comment by mateusfccp** [comment]
As #43 is not being resolved as soon as I though, I am going to make a release with this.

**Comment by mateusfccp** [comment]
@millerf, released version 3.2.0
